# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fcc384117c8f5ddd92ae95686d0f003048fd3ef35d6d01fe05c4573da3bbdb83c359c07e8fd9c7a736ecf245b5d0954048123e69a92a61dd2445b6d8a844d3a9

test:
  secret_key_base: 5f114db41cdfe5a7b160100c2df7f3fd8fc4e32cafe931a13e2f1696cec3cff930e4931514b84578bda7e3a31a0efcc41265ec0ba374ece6acd822ad88a58311

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
